eureka:
  client:
    service-url:
      defaultZone: http://naming-server.private:8761/eureka
spring:
    gateway:
      routes:
        - id: stock-extraction
          uri: lb://stock-extraction
          predicates:
            - Path=/stock-extraction/**
        - id: stock
          uri: lb://stock
          predicates:
            - Path=/stock-register/**
managment: 
  endpoints: 
    web:
      exposure:
        include: "health,info,configprops,mappings,loggers"
